### ISSUE TITLE
Copying Track changes track style into mini coaster

### ISSUE THREAD

**Issue by danielmeinert** [Sadret/openrct2-scenery-manager#30] opened 2022-05-15 21:31 UTC
Currently, when copying track and then pasting (in my case copying wooden coaster track) the pasted track becomes minicoaster. Happens in raw mode.
 
![grafik](https://user-images.githubusercontent.com/39702411/168494671-04991663-2b24-4bf0-aef1-1faa257106de.png)

![grafik](https://user-images.githubusercontent.com/39702411/168494674-983647fe-6d18-4bd8-b391-e04fd61932df.png)

**Comment by Sadret** [comment] 2022-05-15 21:33
Caused by https://github.com/OpenRCT2/OpenRCT2/commit/2bf5f1040ad5172e4d61cc252acce2e3e3b303a3

**Comment by Sadret** [comment] 2022-05-21 08:51
Fixed by https://github.com/OpenRCT2/OpenRCT2/commit/4cc2f3118142ba995c016ae70e87c40f1ffc4f52

**Closed by Sadret** 2022-05-21 08:51 UTC
