### ISSUE TITLE
Feature suggestion: hotkeys

### ISSUE THREAD

**Issue by danielmeinert** [Sadret/openrct2-scenery-manager#13] opened 2021-02-01 15:07 UTC
I don't know if this is planned: hotkey support for the scenery manager would be very useful. I don't know if plugins can access hotkeys though. There don't have to be created new hotkeys for the tool. I think somehow getting access to the tile inspector hotkeys would be already a very good solution. Personally I would only need these three hotkeys (they all work in TI):

lower/raise: basically a hotkey for the height offset box of the blueprint placement
rotation: a hotkey for the rotation box of the blueprint 

additional hotkeys for changing the selection mode and copy mode would be nice too, of course. but as these actions are not done so much so there is not so much of a need I would say

**Comment by danielmeinert** [comment] 2021-02-01 15:10
Sorry, I didn't read the older post where it was suggested already...

**Comment by Sadret** [comment] 2021-02-01 16:36
Duplicate of #2

**Closed by Sadret** 2021-02-01 16:36 UTC
Labels: duplicate
