### ISSUE TITLE
Gridlines disappear when closing brush window

### ISSUE THREAD

**Issue by dragonofmercy** [Sadret/openrct2-scenery-manager#34] opened 2022-08-17 16:00 UTC
Steps to reproduce:
- Enable gridlines display in RCT options
![image](https://user-images.githubusercontent.com/140013/185186937-f0488f08-2313-407d-a58a-27facbedc72d.png)

- Activate a brush
![image](https://user-images.githubusercontent.com/140013/185187188-1f6713fb-360a-441a-9d77-12f8d637840b.png)

- Then close brush window
![image](https://user-images.githubusercontent.com/140013/185187283-5b284d8f-5855-4648-bafa-973e5d8e1dce.png)

**Comment by Sadret** [comment] 2022-08-17 16:49
Duplicate of
https://github.com/Sadret/openrct2-scenery-manager/issues/3
and
https://github.com/OpenRCT2/OpenRCT2/issues/13372

**Closed by Sadret** 2022-08-17 16:49 UTC
