### ISSUE TITLE
Multitile scenery is not copied correctly

### ISSUE THREAD

**Issue by danielmeinert** [Sadret/openrct2-scenery-manager#14] opened 2021-02-01 15:27 UTC
At the moment, when copying an area with a multitile large scenery object, the scenery manager tries to place the whole object on every of the tiles of the original object (this becomes visible with clearence checks disabled), rather than pasting the right corresponding piece of the multitile object into its position. When clearances checks are turned on, the MT object is copied at the wrong position of the selected grid. So probably the code should check to place the MT object only on its (0,0) tile once.

I just realized that this behaviour only happens when 'unavailable elements' errors are turned of. Ok, then the "bug" makes sense of course since MT objects are not supported yet. Then I would request MT support as one of the coming improvements.

**Comment by Sadret** [comment] 2021-02-01 17:08
Caused by: https://github.com/OpenRCT2/OpenRCT2/pull/13651
Already fixed in 3535d36d and will be released with v1.1.5.

**Closed by Sadret** 2021-02-01 17:08 UTC
